version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-paydsub
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD="password"
      - PGPORT=${POSTGRES_PORT}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5
    env_file:
      - .env

volumes:
  postgres_data:
